sudo: required
dist: focal
os: linux
git:
  submodules: false
services:
- docker
env:
  global:
  - PYTHONIOENCODING=UTF8
  - LANGUAGE=wdl
  - secure: q3NlYiEJ6sT1wWNu6mMoZVPtMkUGA5AOB7JdBQyRRq+mqz5z2zVz441/fKsTSQyMUifrfbg4p2C8qKDOZ7v7sA+edia6AYfhDD0Hen55BqW6SdJexH/akRSlWlx2sVjNkKnx4l/6iwj/vGX89HpFb2pPv9stzJXdTOA+rIwRBMfaSqco6j6G3zMA3mui+kEr6v0u86NA3VcLZMPKF95yibeGaUMojw6CB/uSBGsmjjCnCIix7k0cdJMNbRv0vXjdWq2ZTeBCri0qOjUVYZwY2thQUl4/PlufLpncGAR4bOyPl+LOsAmhWLTkVkLtqZ1R0INF7cFiyhxGMuIUuAUe0SkA8tB0w8xZDahboanvZIMYtLuGdUR8aGX4vneW2xv5pU4Lix/HaODqt/84JlAvhKEWdntRSg+avnfJAnWAVRE/yN12xMf1KOjWxHrfIuic22P+wd9CbQkM0jr4xwikZ8LQyjDVrV7BUPfbLVgW/PBqOVy176rOMX+0aUJRv6qfNkcn6HiFOU+YQwyJol/uRdUOoIg2DiyrLADgWTHzVvTxEbNJk06mO+RpjD6zJIdJffDnZ1dXYgnT13iYm4/Wfm46YfFxa5+4D2Eqq87IQfEs9k+oMukGCiReumHijanyfdBoO0jtB1GxLIlrlw7/zqZsG3dfgZbOJ6e3LVE2Duc=
  - secure: IQzjUaWeQv7YPuglbqKAqnwQ6LIOFPxBkKR0GFaL1gOIA4dri8rWggGHf8E4TogeZ2iKzygoaePHc3ZN2zY129jiyrSCwOTwTYoLjDC/HiSUlUfwwflnEYPf1qUYxu/KcWEjl/IDYB6TzmiweV+nGNGREvEs5QS4D7Nad2Y/jdWB1F55T0QKGsFhJBfCZfnDF9NBhZNbw8SstlTyhcQVI59OHeuplE01TQ0Z+Kqkw/oSCRPT5R7Gp1i7Z8NsErpiopyfD1QkuyRJnYnDjNGGnISvHGatPMueQtuThDobDS5xcSft6wZDZw98f2XbEkIUqdYY6QjMbXlQ5LAY3+ZRS+NR7Ede2pHO1WciLmKpM+t6Gztp+Sacuhc9gP/e8PVhvIXj6NuyPEXfP5dl4NpKfk8/ntZTXRupotFy17B1GxhONTr2pOvEFx1coCx8GKLnk7ddV2gE8dmxzoL2cf0GQhDqExC9lzzDAdKE/8m2+/xhLeciwiWIXZc0sCPiZXELTh4bluxpBkGVCAUvx6qIzJZUMzlJYjvaTq94OTL/heBR3FeMM3uRR1mT8x/XRJ9BcLW7nrHRDZ3d9arvVmHBHlI4SPYNm8NSdqEATOMXolOW05SzL4VYGsAyl9X/VQYOMkBzoMwTEbRoCOvpwc5//Olv3Tf3KUriADRU2Lz/2gU=
  - secure: RHMHShcu0HdJgdwj1P6nAo8VLIEQC/FaVpoti7hvpF0w1JPbXpnRb/4UQLs78ZgZ25y5Z5/q1FpdiSrAKhtgv+rmr6BNLoFRk001lcGSbP9i7JayL9UxyC3Mf1nDwNKO+hEiKY9eL6EUa6mKi6ibfBl9+VgU6E9+L1RxCeRRzwTbFc6kYLrE38czOAU7cNcBvn7ulCM99PJIjFgbt/wIzu2T9rjCUtj8KzALKDILX8lca9f+/8oV26zvYSsk5/lyegMeZ/sdEfdbv4lebPPAXBf1AoG2TICXGNAMcIREu+3qSCkMrfhdQRZ0CNBKQEPqpYUda0uOCDp3+Mtg0tUquXEN6hORahPk36TOBoxeS5V5qWs450pp9HcbAustztqd/X4KiF1m8nAvTjdVDlWoUhS59xMHpkta0nZtyRxLwEHEzozn0+feWT/29mJmp7c10soaf8o3/E03vvUSNaSZxekafEuiRepAcCrUMY80wleg9TgPZTdHrO102d1J2N3QZZ56oWUxY6qpKwk0+kZShPT8H59Ng8JPPWXlWC5vCnScm5wm78t99bWKzv4lnO2ls0pASeGd510dr2rp3AKpC2Kl2sdKexuMQUBeay/EL3tBMBd6hImbz/cqD9SuEhQZ0XW2YOWJJ5qcrFSgpdtP82kgHDO3sPUNMEkm6YBLgXU=
branches:
  except:
  - is-branch-info
stages:
- main
jobs:
  fast_finish: true
  include:
  - language: python
    stage: main
    python: '3.8'
    before_install:
    - openssl aes-256-cbc -K $encrypted_6f4cffd5a0cd_key -iv $encrypted_6f4cffd5a0cd_iv
      -in terra/gcloud-config.tar.gz.enc -out terra/gcloud-config.tar.gz -d
    - sudo apt-get update || true
    - sudo apt-get -y install openjdk-8-jre-headless
    install:
    - pip3 -q install firecloud PyYAML
    script:
    - set -e
    - "./travis/test-wdl.sh"
    - tar -xzf terra/gcloud-config.tar.gz -C $HOME
    - git submodule init docker/cms2-docker-component-stats
    - git submodule update --recursive docker/cms2-docker-component-stats
    - "./terra/terra_utils.py deploy_to_terra"
before_install:
- openssl aes-256-cbc -K $encrypted_6f4cffd5a0cd_key -iv $encrypted_6f4cffd5a0cd_iv
  -in gcloud-config.tar.gz.enc -out gcloud-config.tar.gz -d
